### ISSUE TITLE
Text normalization in `list_phones.py`

### ISSUE THREAD

**Issue by ajmalanoski** [CUNY-CL/wikipron#272]
In the Slovenian data, some of the vowels with tone marking (e.g. /é/) are transcribed using the precomposed characters (so here, [U+00E9](https://www.compart.com/en/unicode/U+00E9) instead of the sequence [U+0065](https://www.compart.com/en/unicode/U+0065) [U+0301](https://www.compart.com/en/unicode/U+0301)). The module `ipapy` does not recognize the precomposed characters as valid IPA, so `list_phones.py` incorrectly rejects them. So, I thought it might make sense to normalize the phones as part of `list_phones.py`.

**Comment by kylebgorman** [comment]
Does `ipapy` accept them in NKFD normalization? if so you could just use `unicodedata.normalize` to convert to NFKD, check against `ipapy`, and then convert back.

**Comment by ajmalanoski** [comment]
I tested with several languages and only found one problem with NKFD normalization: <ç> is a valid IPA symbol, but the cedilla is not, so `ipapy.is_valid_ipa(unicodedata.normalize('NFKD', 'ç'))` returns `False`. To solve this, I think we could just check the NFKC normalization in addition to the NFKD normalization. I don't think this will create any problems here, since we're just looking at individual phones.

**Comment by kylebgorman** [comment]
That could work.

1. What happens if we use NFD instead of NFKD?
2. What if we check `is_valid_ipa(nfkd_phone) or phone == "ç"`? Do you think that's simpler than trying both normalizations?

**Comment by ajmalanoski** [comment]
I found two differences between the NFD and NFKD normalizations. First, if we use the NFKD normalization, then `ipapy.is_valid_ipa` will return `False` for anything with an alveolar click symbol <ǃ> in it, because that symbol gets converted to an exclamation point. Second, if we use NFKD normalization, then `ipapy.is_valid_ipa` will accept any superscript consonant or vowel symbols, including those that are not part of the standard IPA repertoire. On the other hand, the NFD normalization leads some valid IPA (e.g. /dⁿ/) to be erroneously rejected. On the whole, however, I think that the NFKD normalization leads bad superscripts to be accepted more often than NFD leads good superscripts to be rejected.

While I was working on this, I discovered that there are a number of instances where a character with a diacritic is included as a key in `ipapy.UNICODE_TO_IPA`, but the diacritic itself is not. For example, <t̼> is in `ipapy.UNICODE_TO_IPA`, but the linguolabial diacritic itself is not. Because of `ipapy.is_valid_ipa` works by checking to see if the individual characters in a string are in `ipapy.UNICODE_TO_IPA`, any string that contains the linguolabial marker will be rejected, even if it shouldn't be. While this isn't exactly the same as the case with <ç> (<◌̧> alone is not an IPA symbol), we can get around both these problems by defining the following set
```
OTHER_VALID_IPA = frozenset(
        phone
        for phone in ipapy.UNICODE_TO_IPA.keys()
        if not ipapy.is_valid_ipa(unicodedata.normalize('NFD', phone))
)
```
and then checking if a phone passes `ipapy.is_valid_ipa` OR is in `OTHER_VALID_IPA`. It's not a perfect solution, because, say, <t̼ː> would still be erroneously rejected, I think.

**Comment by kylebgorman** [comment]
That seems like an improvement to me.

Given how much trouble this is, though, and how recently `ipapy` was added
to this approach, maybe we should just drop it and revert @agutkin's change
there.

**Comment by ajmalanoski** [comment]
It's up to you. I've already made the change on my local copy, though, so I could just push the changes and file a pull request.

**Comment by kylebgorman** [comment]
Let's do the change for now.

**Comment by agutkin** [comment]
Yeah, do it.

But `surely` there must be some better packages out there?

**Comment by kylebgorman** [comment]
Honestly I think I would just maintain a `frozenset` myself for this, if
that's the case.

**Comment by kylebgorman** [comment]
Should this be closed @ajmalanoski or are there outstanding issues here?

**Comment by ajmalanoski** [comment]
I wasn't sure if you wanted me to look for a better package, like @agutkin was suggesting

**Comment by kylebgorman** [comment]
Okay, not a crazy idea, if you want to. Let's keep it open then.

**Comment by sonofthomp** [comment]
> But surely there must be some better packages out there?

I looked around for other IPA modules and I couldn't find any besides ipapy that allow you to easily check if a character is valid IPA. The closest other package is [eng-to-ipa](https://pypi.org/project/eng-to-ipa/), but for whatever reason, it doesn't seem to realize that t̼ or t̼ː are valid IPA characters. Unless someone could find something else I didn't come across, I think it would be best to stick with ipapy.

If the only issue is with the "ː" at the end of characters preventing characters from being considered valid, I think the easiest solution might just be to add all the possible "ː"-suffixed versions of `OTHER_VALID_IPA` characters to `OTHER_VALID_IPA`, like so:

```py
OTHER_VALID_IPA = set(
    phone
    for phone in ipapy.UNICODE_TO_IPA.keys()
    if not ipapy.is_valid_ipa(unicodedata.normalize("NFD", phone))
)

SUFFIXED_OTHER_VALID_IPA = set(
    phone + 'ː'
    for phone in OTHER_VALID_IPA
)

OTHER_VALID_IPA = frozenset(OTHER_VALID_IPA | SUFFIXED_OTHER_VALID_IPA)
```

...so now `OTHER_VALID_IPA` contains both "t̼" and "t̼ː".

The only problem I could see with this is if there are any characters which cannot be suffixed with an "ː" which would be falsely considered valid, or if there's any other suffix characters that aren't accounted for by ipapy (of which I haven't seen any). I don't have a strong phonology background so I'm not sure whether this is the case or not.

**Comment by kylebgorman** [comment]
Thanks for looking into this. I think I am fine with:

* generating a set in which `ː` has been appended to every character
* or, doing so on the fly. That is, when checking whether a string is valid, check each element, and if a lookup fails and the element ends with `ː`, strip it off and look up the remaining character.

This seems like it would scale to other issues that might come up. It may be true that not all IPA characters (including the "chunks" produced by the `segments` model) can have `ː` after them. Every singleton vowel and consonant has, but I have no idea whether [lʲː] is valid (does that mean that it's a long palatalized lateral? Not sure.) I actually don't know though nor do I know whether the IPA (the organization) takes a stance on it either.

**Comment by sonofthomp** [comment]
Cool, I made a PR.

> It may be true that not all IPA characters (including the "chunks" produced by the segments model) can have ː after them. Every singleton vowel and consonant has, but I have no idea whether [lʲː] is valid (does that mean that it's a long palatalized lateral? Not sure.)

I did a Google search but couldn't find an answer to this. I'd say it's probably best to leave it as is for now because it seems to work well enough.

**Comment by agutkin** [comment]
Long laterals are definitely a thing phonetically, e.g. see [here](https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2003/papers/p15_0909.pdf). As for the palatalized version thereof - perhaps it's realisable acoustically in some dialects of Indo-European languages?

**Comment by kylebgorman** [comment]
> Long laterals are definitely a thing phonetically, e.g. see [here](https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2003/papers/p15_0909.pdf). 

The question for me is whether one would transcribe a palatalized lateral with the length mark or something like [lʲlʲ].

**Comment by agutkin** [comment]
I personally would! It's very visually appealing.

**Comment by sonofthomp** [comment]
Should this issue be closed? Idt there's anything else needed to be done here

**Comment by sonofthomp** [comment]
@kylebgorman Should this issue be closed? Idt there's anything else needed to be done here
