### ISSUE TITLE
Persian ~

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/wikipron#379]
Persian, nonstandardly, [uses ~ to separate variants](https://github.com/kylebgorman/wikipron/blob/master/data/tsv/per_phonemic.tsv#L273). Fix these upstream, and then rescrape.

**Comment by aryamanarora** [comment]
The Persian IPA template is due to be superseded by a new Lua version (https://en.wiktionary.org/wiki/Module:fa-IPA). I'll do a bot run to fix this upstream as soon as Wiktionary editors have approved the Lua system.

**Comment by kylebgorman** [comment]
Great news, please update us when that's happened if you can.

**Comment by kylebgorman** [comment]
Is this new template launched yet, @aryamanarora?

**Comment by aryamanarora** [comment]
Haven't gotten any response about it from Wiktionary editors, seems most of the Persian-editing people are inactive. I'll look into it this week to see if it gives the same outputs as the old non-Lua one.

**Comment by kylebgorman** [comment]
Thanks for update.

**Comment by aryamanarora** [comment]
There seem to be slight differences between the old template and the new one (for example, length marking on Tajik-dialect pronunciations). I don't really know much about Persian phonology so don't want to unilaterally go ahead and standardise on the new template, will see if I can get a hold of a Persian editor

**Comment by kylebgorman** [comment]
Hi @aryamanarora, any update on this?

**Comment by aryamanarora** [comment]
There's a bit more than a thousand pages using the new template https://en.wiktionary.org/wiki/Template:fa-IPA, which is one-fifth of all entries. I don't think this is easily automatable yet, since the template requires Classical Persian romanisation (not listed on most pages) to generate dialectal IPA.

**Comment by kylebgorman** [comment]
Okay, so we should probably continue with the manual migration of the "~" entries when we find them

**Comment by sonofthomp** [comment]
For migrating entries from the "\~" format, are you suggesting we replace lines with multiple pronunciations of the same word with several lines, each denoting one pronunciation?

So this:
```
تاجیک	t ɑː d͡ʒ i k ~ t ɑː d͡ʒ iː k
```

Becomes:
```
تاجیک	t ɑː d͡ʒ i k
تاجیک	t ɑː d͡ʒ iː k
```

**Comment by kylebgorman** [comment]
My suggestion is yes, but that we do it upstream (i.e., by editing the few remaining Wiktionary entries with the ~) (and then redownload the data using [this](https://github.com/CUNY-CL/wikipron/blob/749162c74d82aaf1e03446990ff6f32ce3f248f8/data/scrape/scrape.py#L223) and update the copy we have in the big scrape).
