### ISSUE TITLE
Move repo to CUNY-CL?

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/wikipron#417]
I created, a while back, a CUNY-CL organization account on GitHub. Perhaps we should move it there and create a redirect (or just a README with a link). Thoughts?

**Comment by jacksonllee** [comment]
No objection from me about moving it. If you do move it, I _think_ GitHub would automagically redirect all kylebgorman/wikipron links to the equivalent CUNY-CL/wikipron ones, which is nice.

**Comment by kylebgorman** [comment]
Okay, let's find out?

**Comment by jacksonllee** [comment]
Checks out -- straight-up links like https://github.com/kylebgorman/wikipron or https://github.com/kylebgorman/wikipron/tree/v1.2.0 now redirect to the CUNY-CL org as desired. We're all set.
