### ISSUE TITLE
Does it work on Arabic?

### ISSUE THREAD

**Issue by Dallak** [CUNY-CL/wikipron#433]
May I know if this works on Arabic? If so, does it used the IPA symbols for Arabic or other symbols?

**Comment by kylebgorman** [comment]
Yes. It works with virtually every language that has substantial presence on Wiktionary, and that includes (modern standard, and a few other dialects of) Arabic. IPA is used for all languages, just as on Wiktionary. [Here's](https://github.com/CUNY-CL/wikipron/blob/master/data/scrape/tsv/ara_arab_broad.tsv) the pre-scraped MSA data we provide. Install the tool and read the instructions if you'd like to use another configuration.
