### ISSUE TITLE
scraping audio files?

### ISSUE THREAD

**Issue by jhdeov** [CUNY-CL/wikipron#466]
Do you think there's a reasonable way to make an enhancement that will extract audio file URLs for Wiktionary words? At least for Armenian, the audio files are linked in the [Pronunciation](https://en.wiktionary.org/wiki/%D5%A3%D6%80%D5%A5%D5%AC) section.

**Comment by kylebgorman** [comment]
Probably, and at least one person has suggested it would be useful to them.
(I myself don't have a use yet but I like the idea.)

I wonder if this would exceed what we can store on GitHub directly (just in
terms of overall repo size, I think the limit is 5 GB), though, and if so
we would have to do something like make a local download then upload to,
IDK, S3 or something like that and generate a link.

**Comment by jhdeov** [comment]
A possible cheat is that you extract only the URL of the audio file (that I think is hosted on some Wiki domain). Then you can suggest in the README some type of script where a) the user provides a Wikipron-made text file of worth+transcription+URL, and b) the script bulk-downloads the audio files of the URL.

For example, the Wiktionary page of this [word](https://en.m.wiktionary.org/wiki/%D5%A3%D6%80%D5%A5%D5%AC) has a [link](https://en.m.wiktionary.org/wiki/File:Hy-%D5%A3%D6%80%D5%A5%D5%AC.ogg) to an audio file.

I know that the way Wiktionary works is that users independently upload their  audio recordings into some Wiki site. And then Wiktionary links a Wiktionary entry (if it exists) to the audio file (if it exists). That way, a user can make an audio file let's say today, but then next week they make the Wiktionary entry, and then Wiktionary will link the entry with the audio file.

**Comment by rovr** [comment]
> at least one person has suggested it would be useful to them

This would be very useful to me as well (the "word+transcription+URL" combo). Anything I could help with here?

**Comment by kylebgorman** [comment]
There's a paper at LREC that seems to do exactly this: http://www.lrec-conf.org/proceedings/lrec2022/pdf/2022.lrec-1.140.pdf

If it meets the stated need, I'd say that WikiPron doesn't have to do it, you can just merge whatever you want from WikiPron with that source.
