### ISSUE TITLE
`data` package installed

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/wikipron#507]
Because of [this line](https://github.com/CUNY-CL/wikipron/blob/714bd6b34a25c11c544f290bf486dbf0eb141dae/pyproject.toml#L52) we are installing the data module as a package called `data`. Problems with this:

* this is a bit of a generic name for a package!
* constants like [this one](https://github.com/CUNY-CL/wikipron/blob/714bd6b34a25c11c544f290bf486dbf0eb141dae/data/scrape/lib/codes.py#L36) no longer work: they refer to `.json` files that aren't installed

**Comment by jacksonllee** [comment]
When I did https://github.com/CUNY-CL/wikipron/pull/479, I was on the fence about whether to move the `wikipron` package under `src/`, which is something I've already done for all other projects I maintain (in which case we'd have `where = [ "src" ]` for the line you've singled out). I didn't do it in order not to accidentally break things that I might not be aware of, but I guess it's time to reconsider this...

**Comment by kylebgorman** [comment]
@jacksonllee I like that idea, will assign this to myself and do now.
